class MultiLanguageGenerator {
  constructor(tree, variables, symbolTable) {
    this.tree = tree;
    this.variables = variables;
    this.symbolTable = symbolTable || {};
    this.output = '';
    this.indent = 0;
  }

  getType(name) {
    return this.symbolTable[name] || 'int';
  }

  emit(str) {
    this.output += str;
  }

  emitLine(str) {
    if (str.length > 0) {
      this.output += '    '.repeat(this.indent) + str;
    }
    this.output += '\n';
  }

  // ==========================================
  // PYTHON GENERATOR
  // ==========================================
  generatePython() {
    this.output = '';
    this.indent = 0;

    this.emitLine('# Equivalent Python code generated by CompilerFlow');
    this.emitLine('import sys');
    this.emitLine('');

    const funcDecls = [];
    const statementsNode = this.tree.children.find(c => c.type === 'Statements');
    let otherStmts = [];

    if (statementsNode) {
      // Find all functions to output first
      for (const child of statementsNode.children) {
        if (child.type === 'FunctionDeclaration') {
          funcDecls.push(child);
        } else {
          otherStmts.push(child);
        }
      }
    }

    // Emit functions
    for (const func of funcDecls) {
      this.visitPython(func);
      this.emitLine('');
    }

    // Emit main program code
    this.emitLine('def main():');
    this.indent++;
    
    // Initialize variables (since Python does not have declarations, we can set them to default values)
    if (this.variables && this.variables.length > 0) {
      let declaredCount = 0;
      for (const v of this.variables) {
        // Skip function names and parameters
        if (funcDecls.some(f => f.children[1].value === v)) continue;
        let isParam = false;
        for (const func of funcDecls) {
          const paramsNode = func.children[2];
          if (paramsNode && paramsNode.children.some(p => p.value === v)) {
            isParam = true;
            break;
          }
        }
        if (isParam) continue;

        const type = this.getType(v);
        if (type.startsWith('array:')) {
          const size = type.split(':')[1];
          this.emitLine(`${v} = [0] * ${size}`);
        } else if (type === 'string') {
          this.emitLine(`${v} = ""`);
        } else if (type === 'float' || type === 'double') {
          this.emitLine(`${v} = 0.0`);
        } else {
          this.emitLine(`${v} = 0`);
        }
        declaredCount++;
      }
      if (declaredCount > 0) {
        this.emitLine('');
      }
    }

    // Process statements in main
    if (otherStmts.length === 0) {
      this.emitLine('pass');
    } else {
      for (const stmt of otherStmts) {
        this.visitPython(stmt);
      }
    }

    // Also process STOP / END terminals if present
    for (const child of this.tree.children) {
      if (child.type === 'Terminal' && (child.value === 'STOP' || child.value === 'END')) {
        this.emitLine('sys.exit(0)');
      }
    }

    this.indent--;
    this.emitLine('');
    this.emitLine('if __name__ == "__main__":');
    this.indent++;
    this.emitLine('main()');
    this.indent--;

    return this.output;
  }

  visitPython(node) {
    if (!node) return;

    switch (node.type) {
      case 'ReadStatement': {
        for (let i = 1; i < node.children.length; i++) {
          const v = node.children[i].value;
          const type = this.getType(v);
          if (type === 'float' || type === 'double') {
            this.emitLine(`${v} = float(input())`);
          } else if (type === 'string') {
            this.emitLine(`${v} = input()`);
          } else {
            this.emitLine(`${v} = int(input())`);
          }
        }
        break;
      }

      case 'PrintStatement': {
        const expr = node.children[1];
        const pyExpr = this.evalPyExpr(expr);
        this.emitLine(`print(${pyExpr})`);
        break;
      }

      case 'Assignment': {
        const lhs = node.children[0];
        let lhsPy = '';
        if (lhs.type === 'ArrayIndex') {
          const arrId = lhs.children[0].value;
          const idxPy = this.evalPyExpr(lhs.children[1]);
          lhsPy = `${arrId}[${idxPy}]`;
        } else {
          lhsPy = lhs.value;
        }
        const rhsPy = this.evalPyExpr(node.children[2]);
        this.emitLine(`${lhsPy} = ${rhsPy}`);
        break;
      }

      case 'IfStatement': {
        const condPy = this.evalPyCond(node.children[1]);
        this.emitLine(`if ${condPy}:`);
        this.indent++;
        
        const thenStmts = node.children[3];
        if (thenStmts && thenStmts.children.length > 0) {
          for (const s of thenStmts.children) this.visitPython(s);
        } else {
          this.emitLine('pass');
        }
        this.indent--;

        if (node.children.length > 5 && node.children[4].value === 'ELSE') {
          this.emitLine('else:');
          this.indent++;
          const elseStmts = node.children[5];
          if (elseStmts && elseStmts.children.length > 0) {
            for (const s of elseStmts.children) this.visitPython(s);
          } else {
            this.emitLine('pass');
          }
          this.indent--;
        }
        break;
      }

      case 'WhileStatement': {
        const condPy = this.evalPyCond(node.children[1]);
        this.emitLine(`while ${condPy}:`);
        this.indent++;
        const whileStmts = node.children[3];
        if (whileStmts && whileStmts.children.length > 0) {
          for (const s of whileStmts.children) this.visitPython(s);
        } else {
          this.emitLine('pass');
        }
        this.indent--;
        break;
      }

      case 'ForStatement': {
        const loopVar = node.children[1].value;
        const startPy = this.evalPyExpr(node.children[3]);
        const endPy = this.evalPyExpr(node.children[5]);
        const forStmts = node.children[6];

        this.emitLine(`for ${loopVar} in range(${startPy}, ${endPy} + 1):`);
        this.indent++;
        if (forStmts && forStmts.children.length > 0) {
          for (const s of forStmts.children) this.visitPython(s);
        } else {
          this.emitLine('pass');
        }
        this.indent--;
        break;
      }

      case 'SwitchStatement': {
        const swExpr = this.evalPyExpr(node.children[1]);
        const cases = node.children[2];
        
        if (cases && cases.children.length > 0) {
          let isFirst = true;
          for (const cItem of cases.children) {
            if (cItem.type === 'Case') {
              const caseVal = this.evalPyExpr(cItem.children[1]);
              this.emitLine(`${isFirst ? 'if' : 'elif'} ${swExpr} == ${caseVal}:`);
              this.indent++;
              const caseStmts = cItem.children[2];
              // Filter out BREAK terminal from listing
              const pyStmts = caseStmts.children.filter(s => s.value !== 'BREAK');
              if (pyStmts.length > 0) {
                for (const s of pyStmts) this.visitPython(s);
              } else {
                this.emitLine('pass');
              }
              this.indent--;
              isFirst = false;
            } else if (cItem.type === 'DefaultCase') {
              this.emitLine('else:');
              this.indent++;
              const defStmts = cItem.children[1];
              if (defStmts && defStmts.children.length > 0) {
                for (const s of defStmts.children) this.visitPython(s);
              } else {
                this.emitLine('pass');
              }
              this.indent--;
            }
          }
        }
        break;
      }

      case 'RepeatStatement': {
        this.emitLine('while True:');
        this.indent++;
        const repStmts = node.children[1];
        for (const s of repStmts.children) this.visitPython(s);
        const condPy = this.evalPyCond(node.children[3]);
        this.emitLine(`if ${condPy}:`);
        this.indent++;
        this.emitLine('break');
        this.indent--;
        this.indent--;
        break;
      }

      case 'FunctionDeclaration': {
        const funcName = node.children[1].value;
        const params = node.children[2].children.map(p => p.value).join(', ');
        this.emitLine(`def ${funcName}(${params}):`);
        this.indent++;
        const funcStmts = node.children[3];
        if (funcStmts && funcStmts.children.length > 0) {
          for (const s of funcStmts.children) this.visitPython(s);
        } else {
          this.emitLine('pass');
        }
        this.indent--;
        break;
      }

      case 'ReturnStatement': {
        const retVal = this.evalPyExpr(node.children[1]);
        this.emitLine(`return ${retVal}`);
        break;
      }

      default:
        break;
    }
  }

  evalPyCond(node) {
    if (!node || node.type !== 'Condition') return 'True';
    const left = this.evalPyExpr(node.children[0]);
    const op = node.children[1].value;
    const right = this.evalPyExpr(node.children[2]);
    return `${left} ${op} ${right}`;
  }

  evalPyExpr(node) {
    if (!node) return '';
    if (node.type === 'Number' || node.type === 'Identifier' || node.type === 'String') {
      return node.value;
    }
    if (node.type === 'Group') {
      return `(${this.evalPyExpr(node.children[0])})`;
    }
    if (node.type === 'ArrayIndex') {
      return `${node.children[0].value}[${this.evalPyExpr(node.children[1])}]`;
    }
    if (node.type === 'FunctionCall') {
      const funcName = node.children[0].value;
      const args = node.children[1].children.map(a => this.evalPyExpr(a)).join(', ');
      return `${funcName}(${args})`;
    }
    if (node.type === 'Expression') {
      const left = this.evalPyExpr(node.children[0]);
      const op = node.children[1].value;
      const right = this.evalPyExpr(node.children[2]);
      return `${left} ${op} ${right}`;
    }
    return '';
  }


  // ==========================================
  // JAVA GENERATOR
  // ==========================================
  generateJava() {
    this.output = '';
    this.indent = 0;

    this.emitLine('// Equivalent Java code generated by CompilerFlow');
    this.emitLine('import java.util.Scanner;');
    this.emitLine('');
    this.emitLine('public class Main {');
    this.indent++;

    const funcDecls = [];
    const statementsNode = this.tree.children.find(c => c.type === 'Statements');
    let otherStmts = [];

    if (statementsNode) {
      for (const child of statementsNode.children) {
        if (child.type === 'FunctionDeclaration') {
          funcDecls.push(child);
        } else {
          otherStmts.push(child);
        }
      }
    }

    // Java helper functions (static methods outside main)
    for (const func of funcDecls) {
      this.visitJavaFunction(func);
      this.emitLine('');
    }

    // Emit main method
    this.emitLine('public static void main(String[] args) {');
    this.indent++;
    this.emitLine('Scanner scanner = new Scanner(System.in);');
    this.emitLine('');

    // Declarations
    if (this.variables && this.variables.length > 0) {
      const decls = [];
      const groupedVars = { int: [], float: [], char: [], double: [], long: [] };
      
      for (const v of this.variables) {
        if (funcDecls.some(f => f.children[1].value === v)) continue;
        let isParam = false;
        for (const func of funcDecls) {
          const paramsNode = func.children[2];
          if (paramsNode && paramsNode.children.some(p => p.value === v)) {
            isParam = true;
            break;
          }
        }
        if (isParam) continue;

        const type = this.getType(v);
        if (type.startsWith('array:')) {
          const size = type.split(':')[1];
          decls.push(`int[] ${v} = new int[${size}]`);
        } else if (type === 'string') {
          decls.push(`String ${v} = ""`);
        } else {
          if (groupedVars[type]) {
            groupedVars[type].push(v);
          } else {
            groupedVars['int'].push(v);
          }
        }
      }
      
      for (const [type, vars] of Object.entries(groupedVars)) {
        let displayType = type;
        if (type === 'string') displayType = 'String';
        if (vars.length > 0) {
          decls.push(`${displayType} ${vars.join(', ')}`);
        }
      }
      
      if (decls.length > 0) {
        for (const d of decls) {
          this.emitLine(`${d};`);
        }
        this.emitLine('');
      }
    }

    // Process statements in main
    for (const stmt of otherStmts) {
      this.visitJava(stmt);
    }

    // Termination
    for (const child of this.tree.children) {
      if (child.type === 'Terminal' && (child.value === 'STOP' || child.value === 'END')) {
        this.emitLine('System.exit(0);');
      }
    }

    this.indent--;
    this.emitLine('}');

    this.indent--;
    this.emitLine('}');

    return this.output;
  }

  visitJavaFunction(node) {
    // [0] = 'FUNCTION', [1] = id, [2] = parameters, [3] = statements, [4] = 'ENDFUNCTION'
    const funcName = node.children[1].value;
    const paramsNode = node.children[2];
    const funcStmts = node.children[3];
    
    const paramList = [];
    for (const param of paramsNode.children) {
      const pType = this.getType(param.value);
      let pTypeDisplay = pType === 'string' ? 'String' : pType;
      paramList.push(`${pTypeDisplay} ${param.value}`);
    }
    
    this.emitLine(`public static int ${funcName}(${paramList.join(', ')}) {`);
    this.indent++;
    
    // Declare scanner inside function if there is a READ inside it
    const hasRead = this.containsRead(funcStmts);
    if (hasRead) {
      this.emitLine('Scanner scanner = new Scanner(System.in);');
    }

    for (const s of funcStmts.children) {
      this.visitJava(s);
    }

    this.indent--;
    this.emitLine(`}`);
  }

  containsRead(node) {
    if (!node) return false;
    if (node.type === 'ReadStatement') return true;
    if (node.children) {
      return node.children.some(c => this.containsRead(c));
    }
    return false;
  }

  visitJava(node) {
    if (!node) return;

    switch (node.type) {
      case 'ReadStatement': {
        for (let i = 1; i < node.children.length; i++) {
          const v = node.children[i].value;
          const type = this.getType(v);
          if (type === 'float') {
            this.emitLine(`${v} = scanner.nextFloat();`);
          } else if (type === 'double') {
            this.emitLine(`${v} = scanner.nextDouble();`);
          } else if (type === 'string') {
            this.emitLine(`${v} = scanner.next();`);
          } else if (type === 'long') {
            this.emitLine(`${v} = scanner.nextLong();`);
          } else {
            this.emitLine(`${v} = scanner.nextInt();`);
          }
        }
        break;
      }

      case 'PrintStatement': {
        const expr = node.children[1];
        const jExpr = this.evalJavaExpr(expr);
        this.emitLine(`System.out.println(${jExpr});`);
        break;
      }

      case 'Assignment': {
        const lhs = node.children[0];
        let lhsJ = '';
        if (lhs.type === 'ArrayIndex') {
          const arrId = lhs.children[0].value;
          const idxJ = this.evalJavaExpr(lhs.children[1]);
          lhsJ = `${arrId}[${idxJ}]`;
        } else {
          lhsJ = lhs.value;
        }
        const rhsJ = this.evalJavaExpr(node.children[2]);
        this.emitLine(`${lhsJ} = ${rhsJ};`);
        break;
      }

      case 'IfStatement': {
        const condJ = this.evalJavaCond(node.children[1]);
        this.emitLine(`if (${condJ}) {`);
        this.indent++;
        const thenStmts = node.children[3];
        for (const s of thenStmts.children) this.visitJava(s);
        this.indent--;
        
        if (node.children.length > 5 && node.children[4].value === 'ELSE') {
          this.emitLine('} else {');
          this.indent++;
          const elseStmts = node.children[5];
          for (const s of elseStmts.children) this.visitJava(s);
          this.indent--;
        }
        this.emitLine('}');
        break;
      }

      case 'WhileStatement': {
        const condJ = this.evalJavaCond(node.children[1]);
        this.emitLine(`while (${condJ}) {`);
        this.indent++;
        const whileStmts = node.children[3];
        for (const s of whileStmts.children) this.visitJava(s);
        this.indent--;
        this.emitLine('}');
        break;
      }

      case 'ForStatement': {
        const loopVar = node.children[1].value;
        const startJ = this.evalJavaExpr(node.children[3]);
        const endJ = this.evalJavaExpr(node.children[5]);
        const forStmts = node.children[6];

        this.emitLine(`for (${loopVar} = ${startJ}; ${loopVar} <= ${endJ}; ${loopVar}++) {`);
        this.indent++;
        for (const s of forStmts.children) this.visitJava(s);
        this.indent--;
        this.emitLine('}');
        break;
      }

      case 'SwitchStatement': {
        const swExpr = this.evalJavaExpr(node.children[1]);
        this.emitLine(`switch (${swExpr}) {`);
        this.indent++;
        const cases = node.children[2];
        if (cases) {
          for (const cItem of cases.children) {
            if (cItem.type === 'Case') {
              const caseVal = this.evalJavaExpr(cItem.children[1]);
              this.emitLine(`case ${caseVal}:`);
              this.indent++;
              const caseStmts = cItem.children[2];
              for (const s of caseStmts.children) this.visitJava(s);
              if (cItem.children.some(c => c.value === 'BREAK')) {
                this.emitLine('break;');
              }
              this.indent--;
            } else if (cItem.type === 'DefaultCase') {
              this.emitLine('default:');
              this.indent++;
              const defStmts = cItem.children[1];
              for (const s of defStmts.children) this.visitJava(s);
              this.indent--;
            }
          }
        }
        this.emitLine('}');
        break;
      }

      case 'RepeatStatement': {
        this.emitLine('do {');
        this.indent++;
        const repStmts = node.children[1];
        for (const s of repStmts.children) this.visitJava(s);
        this.indent--;
        const condJ = this.evalJavaCond(node.children[3]);
        this.emitLine(`} while (!(${condJ}));`);
        break;
      }

      case 'ReturnStatement': {
        const retVal = this.evalJavaExpr(node.children[1]);
        this.emitLine(`return ${retVal};`);
        break;
      }

      default:
        break;
    }
  }

  evalJavaCond(node) {
    if (!node || node.type !== 'Condition') return 'true';
    const left = this.evalJavaExpr(node.children[0]);
    const op = node.children[1].value;
    const right = this.evalJavaExpr(node.children[2]);
    return `${left} ${op} ${right}`;
  }

  evalJavaExpr(node) {
    if (!node) return '';
    if (node.type === 'Number' || node.type === 'Identifier' || node.type === 'String') {
      return node.value;
    }
    if (node.type === 'Group') {
      return `(${this.evalJavaExpr(node.children[0])})`;
    }
    if (node.type === 'ArrayIndex') {
      return `${node.children[0].value}[${this.evalJavaExpr(node.children[1])}]`;
    }
    if (node.type === 'FunctionCall') {
      const funcName = node.children[0].value;
      const args = node.children[1].children.map(a => this.evalJavaExpr(a)).join(', ');
      return `${funcName}(${args})`;
    }
    if (node.type === 'Expression') {
      const left = this.evalJavaExpr(node.children[0]);
      const op = node.children[1].value;
      const right = this.evalJavaExpr(node.children[2]);
      return `${left} ${op} ${right}`;
    }
    return '';
  }


  // ==========================================
  // X86 ASSEMBLY GENERATOR
  // ==========================================
  generateAssembly() {
    this.output = '';
    this.indent = 0;

    this.emitLine('; Equivalent x86 Intel Assembly code generated by CompilerFlow');
    this.emitLine('section .data');
    this.indent++;
    this.emitLine('format_in db "%d", 0');
    this.emitLine('format_out db "%d", 10, 0');
    
    // Allocate variables
    if (this.variables && this.variables.length > 0) {
      for (const v of this.variables) {
        const type = this.getType(v);
        if (type.startsWith('array:')) {
          const size = type.split(':')[1];
          this.emitLine(`${v} times ${size} dd 0`);
        } else {
          this.emitLine(`${v} dd 0`);
        }
      }
    }
    this.indent--;
    this.emitLine('');

    this.emitLine('section .text');
    this.indent++;
    this.emitLine('global main');
    this.emitLine('extern printf');
    this.emitLine('extern scanf');
    this.emitLine('');

    this.emitLine('main:');
    this.indent++;
    this.emitLine('push ebp');
    this.emitLine('mov ebp, esp');
    this.emitLine('');

    // Translate statements
    const statementsNode = this.tree.children.find(c => c.type === 'Statements');
    if (statementsNode) {
      for (const stmt of statementsNode.children) {
        if (stmt.type !== 'FunctionDeclaration') {
          this.visitAsm(stmt);
        }
      }
    }

    this.emitLine('');
    this.emitLine('mov eax, 0'); // exit code 0
    this.emitLine('mov esp, ebp');
    this.emitLine('pop ebp');
    this.emitLine('ret');
    this.indent--;
    this.indent--;

    return this.output;
  }

  visitAsm(node) {
    if (!node) return;

    this.emitLine(`; Statement: ${node.type}`);

    switch (node.type) {
      case 'ReadStatement': {
        for (let i = 1; i < node.children.length; i++) {
          const v = node.children[i].value;
          this.emitLine(`push ${v}`);
          this.emitLine('push format_in');
          this.emitLine('call scanf');
          this.emitLine('add esp, 8');
        }
        break;
      }

      case 'PrintStatement': {
        const expr = node.children[1];
        if (expr.type === 'Number' || expr.type === 'Identifier') {
          const operand = expr.type === 'Number' ? expr.value : `[${expr.value}]`;
          this.emitLine(`push dword ${operand}`);
        } else {
          this.evalAsmExpr(expr);
          this.emitLine('push eax');
        }
        this.emitLine('push format_out');
        this.emitLine('call printf');
        this.emitLine('add esp, 8');
        break;
      }

      case 'Assignment': {
        const lhs = node.children[0];
        const rhs = node.children[2];
        
        this.evalAsmExpr(rhs); // result in EAX
        
        if (lhs.type === 'ArrayIndex') {
          const arrId = lhs.children[0].value;
          this.emitLine('push eax'); // Save RHS value
          this.evalAsmExpr(lhs.children[1]); // Index value in EAX
          this.emitLine('mov ecx, eax'); // ECX = Index
          this.emitLine('pop eax'); // Restore RHS value
          this.emitLine(`mov [${arrId} + ecx*4], eax`);
        } else {
          this.emitLine(`mov [${lhs.value}], eax`);
        }
        break;
      }

      case 'IfStatement': {
        const cond = node.children[1];
        const labelElse = `_L_else_${Math.floor(Math.random() * 10000)}`;
        const labelEnd = `_L_end_${Math.floor(Math.random() * 10000)}`;
        
        const hasElse = node.children.length > 5 && node.children[4].value === 'ELSE';

        this.evalAsmCond(cond, hasElse ? labelElse : labelEnd, false); // jump if false
        
        const thenStmts = node.children[3];
        for (const s of thenStmts.children) this.visitAsm(s);
        
        if (hasElse) {
          this.emitLine(`jmp ${labelEnd}`);
          this.emitLine(`${labelElse}:`);
          const elseStmts = node.children[5];
          for (const s of elseStmts.children) this.visitAsm(s);
        }
        
        this.emitLine(`${labelEnd}:`);
        break;
      }

      case 'WhileStatement': {
        const cond = node.children[1];
        const labelStart = `_L_while_start_${Math.floor(Math.random() * 10000)}`;
        const labelEnd = `_L_while_end_${Math.floor(Math.random() * 10000)}`;

        this.emitLine(`${labelStart}:`);
        this.evalAsmCond(cond, labelEnd, false); // jump if false
        
        const whileStmts = node.children[3];
        for (const s of whileStmts.children) this.visitAsm(s);
        
        this.emitLine(`jmp ${labelStart}`);
        this.emitLine(`${labelEnd}:`);
        break;
      }

      case 'ForStatement': {
        const loopVar = node.children[1].value;
        const startExpr = node.children[3];
        const endExpr = node.children[5];
        const forStmts = node.children[6];

        const labelStart = `_L_for_start_${Math.floor(Math.random() * 10000)}`;
        const labelEnd = `_L_for_end_${Math.floor(Math.random() * 10000)}`;

        this.evalAsmExpr(startExpr);
        this.emitLine(`mov [${loopVar}], eax`); // loopVar = start

        this.emitLine(`${labelStart}:`);
        this.evalAsmExpr(endExpr);
        this.emitLine('mov ecx, eax'); // ECX = end value
        this.emitLine(`mov edx, [${loopVar}]`); // EDX = loopVar value
        this.emitLine('cmp edx, ecx');
        this.emitLine(`jg ${labelEnd}`); // if loopVar > end, jump to end

        for (const s of forStmts.children) this.visitAsm(s);

        this.emitLine(`inc dword [${loopVar}]`);
        this.emitLine(`jmp ${labelStart}`);
        this.emitLine(`${labelEnd}:`);
        break;
      }

      default:
        break;
    }
  }

  evalAsmExpr(node) {
    if (!node) return;

    if (node.type === 'Number') {
      this.emitLine(`mov eax, ${node.value}`);
      return;
    }

    if (node.type === 'Identifier') {
      this.emitLine(`mov eax, [${node.value}]`);
      return;
    }

    if (node.type === 'Group') {
      this.evalAsmExpr(node.children[0]);
      return;
    }

    if (node.type === 'ArrayIndex') {
      const arrId = node.children[0].value;
      this.evalAsmExpr(node.children[1]); // Index value in EAX
      this.emitLine(`mov eax, [${arrId} + eax*4]`);
      return;
    }

    if (node.type === 'Expression') {
      const left = node.children[0];
      const op = node.children[1].value;
      const right = node.children[2];

      this.evalAsmExpr(left);
      this.emitLine('push eax'); // push left value
      this.evalAsmExpr(right);
      this.emitLine('mov ebx, eax'); // EBX = right value
      this.emitLine('pop eax'); // EAX = left value

      switch (op) {
        case '+':
          this.emitLine('add eax, ebx');
          break;
        case '-':
          this.emitLine('sub eax, ebx');
          break;
        case '*':
          this.emitLine('imul eax, ebx');
          break;
        case '/':
          this.emitLine('cdq'); // Sign-extend EAX into EDX:EAX
          this.emitLine('idiv ebx'); // EAX = EAX / EBX
          break;
      }
    }
  }

  evalAsmCond(condNode, label, jumpOnTrue) {
    if (!condNode || condNode.type !== 'Condition') return;
    const left = condNode.children[0];
    const op = condNode.children[1].value;
    const right = condNode.children[2];

    this.evalAsmExpr(left);
    this.emitLine('push eax');
    this.evalAsmExpr(right);
    this.emitLine('mov ebx, eax'); // EBX = right
    this.emitLine('pop eax'); // EAX = left
    this.emitLine('cmp eax, ebx');

    if (jumpOnTrue) {
      switch (op) {
        case '==': this.emitLine(`je ${label}`); break;
        case '!=': this.emitLine(`jne ${label}`); break;
        case '>': this.emitLine(`jg ${label}`); break;
        case '<': this.emitLine(`jl ${label}`); break;
        case '>=': this.emitLine(`jge ${label}`); break;
        case '<=': this.emitLine(`jle ${label}`); break;
      }
    } else {
      // Jump if false (negated jump)
      switch (op) {
        case '==': this.emitLine(`jne ${label}`); break;
        case '!=': this.emitLine(`je ${label}`); break;
        case '>': this.emitLine(`jle ${label}`); break;
        case '<': this.emitLine(`jge ${label}`); break;
        case '>=': this.emitLine(`jl ${label}`); break;
        case '<=': this.emitLine(`jg ${label}`); break;
      }
    }
  }
}

module.exports = MultiLanguageGenerator;
